version: '3'

services:
  app:
    image: findfacts/findfacts:0.1.0-SNAPSHOT
    container_name: prod_app
    restart: always
    env_file:
      - app.env
      - server.env
    environment:
      - VIRTUAL_PORT=9000
      - SOLR_HOST=solr
    logging:
      driver: syslog
      options:
        syslog-address: "tcp://localhost:514"
        tag: "{{.Name}}"
    expose:
      - 9000
    ports:
      - 9000:9000
    networks:
      - infrastructure_proxy
      - solr820_internal

networks:
  infrastructure_proxy:
    external: true
  solr820_internal:
    external: true
